version: '3.8'

services:
  server-blue:
    image: s13121312/capstoneback:latest
    container_name: capstone-server-blue
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    networks:
      - capstone-net
    restart: always
    depends_on:
      my-db:
        condition: service_healthy
      my-cache-server:
        condition: service_healthy

  server-green:
    image: s13121312/capstoneback:latest
    container_name: capstone-server-green
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    networks:
      - capstone-net
    restart: always
    depends_on:
      my-db:
        condition: service_healthy
      my-cache-server:
        condition: service_healthy


  nginx:
    image: nginx:latest
    container_name: nginx-capstone
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: always
    networks:
      - capstone-net

  my-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: capstone1234!
      MYSQL_DATABASE: capstonedb
    command: --innodb_buffer_pool_size=128M --max_connections=20  #메모리 사용량을 128MB로 제한 동시 연결 수를 줄임
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    # 네트워크 할당
    networks:
      - capstone-net

  my-cache-server:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - capstone-net

  ai-worker:
    build:
      context: . # 현재 디렉토리를 빌드 컨텍스트로 사용
      dockerfile: AI/Dockerfile # AI 폴더 내부의 Dockerfile 지정
    container_name: capstone-ai-worker
    image: capstone-ai-worker:latest
    env_file:
      - .env # Redis 비밀번호 등 공유 환경 변수 로드
    environment:
      # [Redis Streams 설정] Service Name이 호스트 이름이 됨
      REDIS_HOST: my-cache-server
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD} # .env 파일에서 가져옴
      # [Spring Callback Target]
      # 이 값은 배포 스크립트에서 동적으로 설정됨
      SPRING_CALLBACK_URL: http://capstone-server-blue:8080/api/callback/speech/non-verbal
      TZ: Asia/Seoul
    restart: always
    depends_on:
      my-cache-server: # Redis가 살아 있어야 작업을 시작할 수 있음
        condition: service_healthy
    networks:
      - capstone-net

# 사용할 네트워크
networks:
  capstone-net:
    driver: bridge