spring:
  datasource:
    url: jdbc:mysql://my-db:3306/capstonedb
    username: root
    password: capstone1234!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: my-cache-server
      port: 6379
  jwt:
    access:
      plus-hour: 1   # 1시간
    refresh:
      plus-hour: 168   # 24*7 7일
    secret: ${JWT_SECRET}
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      base-url: https://api.openai.com/
      model: gpt-4o-mini
      chat:
        options:
          stream: false
      whisper:
        model: whisper-1
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB


cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}  # bucket 이름을 설정한다.
    region:
      static: ${S3_REGION} # bucket이 위치한 AWS 리전을 설정한다.
    stack:
      auto: false # 자동 스택 생성 기능 사용여부를 설정한다. (자동 스택 생성: 애플리케이션이 실행, 배포될 때 인프라 리소스를 자동으로 생성하고 설정하는 것)

oauth:
  kakao:
    redirect-uri: http://localhost:8080/api/auth/test
    base-url: https://kauth.kakao.com
    app-key: ${KAKAO_APP_KEY}
