apiVersion: 1

datasources:
  - name: Prometheus (provisioned)
    uid: prometheus-monitoring
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
